# Generated by Django 5.0.2 on 2024-02-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_spreadsheetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_model',
            name='screenshot',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
